### ISSUE TITLE
Invalid configuration object

### ISSUE THREAD

**Issue by matt-lethargic** [detroitenglish/cloudflare-workers-webpack-boilerplate#4]
I'm getting an error 

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "dist" is not an absolute path!
   -> The output directory as **absolute path** (required).
```

my background is C# so am not up-to-date with webpack and npm enough to fix diagnose this. Any help would be great

**Comment by detroitenglish** [comment]
Thanks for reporting this, Matt. And thanks for mentioning your C# background - I inferred the issue was with `win32` systems, so I tested on Windows and discovered I was accidentally resolving paths as `posix`.

[Fixed in 2.2.3](https://github.com/detroitenglish/cloudflare-workers-webpack-boilerplate/commit/aeca4de7a9a2080bfab13e025e7e1205b78583b0), and tested on Windows 10. Cheers! 🍻
